# Generated by Django 3.0.4 on 2020-04-11 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_num', models.IntegerField(verbose_name='Номер урока')),
                ('title', models.CharField(max_length=50, verbose_name='Название урока')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Speechpart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=20, verbose_name='Часть речи')),
            ],
            options={
                'verbose_name': 'Часть речи',
                'verbose_name_plural': 'Части речи',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_name', models.CharField(max_length=30, verbose_name='Номер урока')),
                ('transcription', models.CharField(max_length=30, verbose_name='Название урока')),
                ('word_translation', models.TextField(max_length=50, verbose_name='Перевод слова')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Lesson')),
                ('speechpart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Speechpart')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji_name', models.CharField(max_length=5, verbose_name='Иероглиф')),
                ('meanings', models.CharField(max_length=50, verbose_name='Значение')),
                ('kunyomi', models.TextField(max_length=10, verbose_name='Кунное чтение')),
                ('onyomi', models.TextField(max_length=10, verbose_name='Онное чтение')),
                ('linesqty', models.IntegerField(verbose_name='Количество черт')),
                ('code', models.CharField(max_length=5, verbose_name='Код')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.Lesson')),
            ],
            options={
                'verbose_name': 'Иероглиф',
                'verbose_name_plural': 'Иероглифы',
            },
        ),
    ]
