# Generated by Django 3.0.4 on 2020-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_acad_perfomance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст урока'),
        ),
    ]
