# Generated by Django 3.0.4 on 2020-05-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kanjis', to='lessons.Lesson'),
        ),
        migrations.AlterField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='lessons.Lesson'),
        ),
        migrations.DeleteModel(
            name='Acad_perfomance',
        ),
    ]
