# Generated by Django 3.0.4 on 2020-06-08 19:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20200519_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
