# Generated by Django 3.0.4 on 2020-06-08 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ans_option',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=8), size=8),
        ),
    ]
