# Generated by Django 3.0.4 on 2021-01-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='icon',
            field=models.ImageField(blank=True, help_text='Group icon', upload_to='chartgroup'),
        ),
    ]
