# Generated by Django 3.0.4 on 2020-05-06 17:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('m_role', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=10, verbose_name='Роль')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(max_length=50, verbose_name='Информация')),
                ('group_num', models.CharField(choices=[('J20-1', 'j20-1'), ('J20-2', 'j20-2')], default='J20-1', max_length=50, verbose_name='Номер группы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
