# Generated by Django 3.0.4 on 2020-05-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='m_role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Administrator', 'Administrator')], default='Student', max_length=15, verbose_name='Роль'),
        ),
    ]
