# Generated by Django 3.0.4 on 2020-05-16 15:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20200516_2256'),
        ('users', '0002_auto_20200513_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acad_perfomance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_num', models.IntegerField(verbose_name='Номер задания')),
                ('rights', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=8), size=8)),
                ('wrongs', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=8), size=8)),
                ('datetime', models.DateTimeField()),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfomances', to='lessons.Lesson')),
                ('seito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.Profile')),
            ],
            options={
                'verbose_name': 'Успеваемость',
                'verbose_name_plural': 'Успеваемость',
            },
        ),
    ]
