# Generated by Django 3.0.4 on 2021-01-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_acad_perfomance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
